//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItWebApplication.WordCountServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordCountServiceReference.WordCountIService")]
    public interface WordCountIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WordCountIService/c2f", ReplyAction="http://tempuri.org/WordCountIService/c2fResponse")]
        int c2f(int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WordCountIService/c2f", ReplyAction="http://tempuri.org/WordCountIService/c2fResponse")]
        System.Threading.Tasks.Task<int> c2fAsync(int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WordCountIService/WordCount", ReplyAction="http://tempuri.org/WordCountIService/WordCountResponse")]
        string WordCount(System.IO.Stream file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WordCountIService/WordCount", ReplyAction="http://tempuri.org/WordCountIService/WordCountResponse")]
        System.Threading.Tasks.Task<string> WordCountAsync(System.IO.Stream file);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WordCountIServiceChannel : TryItWebApplication.WordCountServiceReference.WordCountIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordCountIServiceClient : System.ServiceModel.ClientBase<TryItWebApplication.WordCountServiceReference.WordCountIService>, TryItWebApplication.WordCountServiceReference.WordCountIService {
        
        public WordCountIServiceClient() {
        }
        
        public WordCountIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordCountIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordCountIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordCountIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int c2f(int c) {
            return base.Channel.c2f(c);
        }
        
        public System.Threading.Tasks.Task<int> c2fAsync(int c) {
            return base.Channel.c2fAsync(c);
        }
        
        public string WordCount(System.IO.Stream file) {
            return base.Channel.WordCount(file);
        }
        
        public System.Threading.Tasks.Task<string> WordCountAsync(System.IO.Stream file) {
            return base.Channel.WordCountAsync(file);
        }
    }
}
