//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItWebApplication.ChatGPTServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatGPTServiceReference.IChatGPTService")]
    public interface IChatGPTService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatGPTService/AskChatGPTAboutUrl", ReplyAction="http://tempuri.org/IChatGPTService/AskChatGPTAboutUrlResponse")]
        string AskChatGPTAboutUrl(string question, string[] resources, string chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatGPTService/AskChatGPTAboutUrl", ReplyAction="http://tempuri.org/IChatGPTService/AskChatGPTAboutUrlResponse")]
        System.Threading.Tasks.Task<string> AskChatGPTAboutUrlAsync(string question, string[] resources, string chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatGPTService/getChat", ReplyAction="http://tempuri.org/IChatGPTService/getChatResponse")]
        string getChat(string chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatGPTService/getChat", ReplyAction="http://tempuri.org/IChatGPTService/getChatResponse")]
        System.Threading.Tasks.Task<string> getChatAsync(string chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatGPTService/AskChatGPT", ReplyAction="http://tempuri.org/IChatGPTService/AskChatGPTResponse")]
        string AskChatGPT(string question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatGPTService/AskChatGPT", ReplyAction="http://tempuri.org/IChatGPTService/AskChatGPTResponse")]
        System.Threading.Tasks.Task<string> AskChatGPTAsync(string question);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatGPTServiceChannel : TryItWebApplication.ChatGPTServiceReference.IChatGPTService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatGPTServiceClient : System.ServiceModel.ClientBase<TryItWebApplication.ChatGPTServiceReference.IChatGPTService>, TryItWebApplication.ChatGPTServiceReference.IChatGPTService {
        
        public ChatGPTServiceClient() {
        }
        
        public ChatGPTServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChatGPTServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatGPTServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatGPTServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AskChatGPTAboutUrl(string question, string[] resources, string chatId) {
            return base.Channel.AskChatGPTAboutUrl(question, resources, chatId);
        }
        
        public System.Threading.Tasks.Task<string> AskChatGPTAboutUrlAsync(string question, string[] resources, string chatId) {
            return base.Channel.AskChatGPTAboutUrlAsync(question, resources, chatId);
        }
        
        public string getChat(string chatId) {
            return base.Channel.getChat(chatId);
        }
        
        public System.Threading.Tasks.Task<string> getChatAsync(string chatId) {
            return base.Channel.getChatAsync(chatId);
        }
        
        public string AskChatGPT(string question) {
            return base.Channel.AskChatGPT(question);
        }
        
        public System.Threading.Tasks.Task<string> AskChatGPTAsync(string question) {
            return base.Channel.AskChatGPTAsync(question);
        }
    }
}
